version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ai_tools_db
      POSTGRES_USER: user_ai_tools
      POSTGRES_PASSWORD: rDKAJKdfnwejk2344nNdskfsfsmdfbnj(32)
    ports:
      - "5430:5432"
    networks:
      - app-network-ai-tools
    volumes:
      - postgres_data_ai_tools:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_ai_tools -d ai_tools_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Có thể thêm các middleware service khác ở đây
  # Ví dụ: redis, rabbitmq, elasticsearch, etc.

volumes:
  postgres_data_ai_tools:

networks:
  app-network-ai-tools:
    driver: bridge 