version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://ai-tools-api.hacknao.edu.vn/api
    ports:
      - "3009:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://ai-tools-api.hacknao.edu.vn/api
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network-ai-tools

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5008:5008"
    environment:
      FLASK_ENV: production
      FLASK_APP: run.py
    restart: unless-stopped
    networks:
      - app-network-ai-tools
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ai_tools_db
      POSTGRES_USER: user_ai_tools
      POSTGRES_PASSWORD: rDKAJKdfnwejk2344nNdskfsfsmdfbnj(32)
    ports:
      - "5430:5432"
    networks:
      - app-network-ai-tools
    volumes:
      - postgres_data_ai_tools:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_ai_tools -d ai_tools_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_ai_tools:

networks:
  app-network-ai-tools:
    driver: bridge